### ISSUE TITLE
Fails to import

### ISSUE THREAD

**Issue by mr-modz** [zhuowei/MCPELauncher#1035]
I try to import a mod and this pops up

org.mozilla.javascript.WrappedException: Wrapped net.zhuoweizhang.mcpelauncher.MissingTextureException: The item icon jpkemty:0 does not exist (SuperJetPack.js#16)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(SuperJetPack.js:16)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:267)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:192)
	at java.lang.Thread.run(Thread.java:841)
Caused by: net.zhuoweizhang.mcpelauncher.MissingTextureException: The item icon jpkemty:0 does not exist
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeModPEApi.setItem(ScriptManager.java:3317)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	... 11 more

**Comment by Black-DeathPE** [comment]
That's an issue you should send to the creator of that mod.

**Comment by mr-modz** [comment]
I don't think it's the creator of the mod because it doesn't import for all of the mods





Sent from my Samsung Galaxy Tab®4


-------- Original message --------

**Comment by Roundcoolkid97** [comment]
No it's because you need to install the texture pack first then the script

**Comment by Aternix** [comment]
Yes, you need them too but it doesn't still works... 

Idk whymy coded custom items isn't works.

Trying to import Effect swords mod... then it show errors.

**Comment by Aternix** [comment]
Oh wait! They need var things!!

**Comment by Aternix** [comment]
I try to work it then it actually do!
