### ISSUE TITLE
Help me for this code

### ISSUE THREAD

**Issue by Aternix** [zhuowei/MCPELauncher#1050]
Error:

org.mozilla.javascript.EvaluatorException: missing } after function body (Blood Excalibur Mod.js#114)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(Unknown Source)
	at org.mozilla.javascript.DefaultErrorReporter.error(Unknown Source)
	at org.mozilla.javascript.Parser.addError(Unknown Source)
	at org.mozilla.javascript.Parser.reportError(Unknown Source)
	at org.mozilla.javascript.Parser.reportError(Unknown Source)
	at org.mozilla.javascript.Parser.mustMatchToken(Unknown Source)
	at org.mozilla.javascript.Parser.mustMatchToken(Unknown Source)
	at org.mozilla.javascript.Parser.parseFunctionBody(Unknown Source)
	at org.mozilla.javascript.Parser.function(Unknown Source)
	at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
	at org.mozilla.javascript.Parser.statement(Unknown Source)
	at org.mozilla.javascript.Parser.statements(Unknown Source)
	at org.mozilla.javascript.Parser.block(Unknown Source)
	at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
	at org.mozilla.javascript.Parser.statement(Unknown Source)
	at org.mozilla.javascript.Parser.ifStatement(Unknown Source)
	at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
	at org.mozilla.javascript.Parser.statement(Unknown Source)
	at org.mozilla.javascript.Parser.parseFunctionBody(Unknown Source)
	at org.mozilla.javascript.Parser.function(Unknown Source)
	at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
	at org.mozilla.javascript.Parser.statement(Unknown Source)
	at org.mozilla.javascript.Parser.statements(Unknown Source)
	at org.mozilla.javascript.Parser.block(Unknown Source)
	at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
	at org.mozilla.javascript.Parser.statement(Unknown Source)
	at org.mozilla.javascript.Parser.ifStatement(Unknown Source)
	at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
	at org.mozilla.javascript.Parser.statement(Unknown Source)
	at org.mozilla.javascript.Parser.parseFunctionBody(Unknown Source)
	at org.mozilla.javascript.Parser.function(Unknown Source)
	at org.mozilla.javascript.Parser.parse(Unknown Source)
	at org.mozilla.javascript.Parser.parse(Unknown Source)
	at org.mozilla.javascript.Context.compileImpl(Unknown Source)
	at org.mozilla.javascript.Context.compileReader(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:191)
	at java.lang.Thread.run(Thread.java:856)

My Script:

var bloodgem = 1001;
var bloodexca = 1003;
var blood = 1000;
var exca = 1004;
var bloodcrys = 1002;
var blooddag = 1005;
var blhelmet = 1006;
var blchest = 1007;
var bllegg = 1008;
var blboots = 1009;

var ctx = com.mojang.minecraftpe.MainActivity.currentMainActivity.get();
function newLevel(){
clientMessage(ChatColor.RED + "§lBlood Excalibur Mod [v1.0]");
clientMessage(ChatColor.RED + "By Aternix");
clientMessage(ChatColor.RED + "In SURVIVAL mode: Type /blood in chat to add §citems");
ctx.runOnUiThread(new java.lang.Runnable(){
run: function(){
try{
android.widget.Toast.makeText(ctx, new android.text.Html.fromHtml("INTIALIZED"),0).show();
android.widget.Toast.makeText(ctx, new android.text.Html.fromHtml("BY ATERNIX"),0).show()
}catch (err){
clientMessage("Error: " + err)
}}})}

function procCmd(cmd) {
	var com = cmd.split(" ");
  	if(com[0]=="blood"){
    	clientMessage("§cBlood items are added in your inventory")
		for(i=1000; i<1006; i++){
		    Player.addItemInventory(i, 1, 0);
		}
  	}
}

ModPE.setItem(bloodgem,"record_blocks",0,"Blood Gem",0);
ModPE.setItem(bloodexca,"record_mall",0,"Blood Excalibur",0);
ModPE.setItem(blood,"record_11",0,"Blood",0);
ModPE.setItem(blooddag,"record_cat",0,"Blood Dagger",0);
ModPE.setItem(exca,"record_mellohi",0,"Excalibur",0);
ModPE.setItem(bloodcrys,"record_13",0,"Blood Crystal",0);
ModPE.setItem(blhelmet,"record_stal",0,"Blood Helmet",0);
ModPE.setItem(blchest,"record_far",0,"Blood Chestplate",0);
ModPE.setItem(bllegg,"record_ward",0,"Blood Leggings",0);
ModPE.setItem(blboots,"record_chirp",0,"Blood Boots",0);

Item.setHandEquipped(bloodexca,1);
Item.setHandEquipped(blooddag,1);
Item.setHandEquipped(exca,1);
Item.setMaxDamage(bloodexca,14500);
Item.setMaxDamage(blooddag,8000);
Item.setMaxDamage(exca,9000);

Player.addItemCreativeInv(bloodgem,64,0);
Player.addItemCreativeInv(bloodexca,1,0);
Player.addItemCreativeInv(blood,64,0);
Player.addItemCreativeInv(blooddag,1,0);
Player.addItemCreativeInv(exca,1,0);
Player.addItemCreativeInv(bloodcrys,64,0);
Player.addItemCreativeInv(blhelmet,1,0);
Player.addItemCreativeInv(blchest,1,0);
Player.addItemCreativeInv(bllegg,1,0);
Player.addItemCreativeInv(blboots,64,0);

Item.addShapedRecipe(blooddag,1,0,[" 1 "," 1 ","232"],["1",1000,0,"2",1002,0,"3",264,0]);
Item.addShapedRecipe(bloodexca,1,0,["111","121","131"],["1",1000,0,"2",1007,0,"3",1001,0]);
Item.addShapedRecipe(bloodcrys,1,0,["111","121","111"],["1",1002,0,"2",264,0]);
Item.addShapedRecipe(bloodgem,1,0,["111","111","111"],["1",1009,0]);
Item.addShapedRecipe(blhelmet,1,0,["222","212","   "],["1",1000,0,"2",1002,0]);
Item.addShapedRecipe(bloodchest,1,0,["121","111","111"],["1",1002,0,"2",1000,0]);
Item.addShapedRecipe(bllegg,1,0,["111","121","1 1"],["1",1002,0,"2",1000,0]);
Item.addShapedRecipe(blboots,1,0,["   ","212","2 2"],["1",1000,0,"2",1002,0]);
Item.defineArmor(blhelmet,"record_blocks",0,"Blood Helmet","armor/armor1.png",2,1150,ArmorType.helmet);
Item.defineArmor(blchest,"record_cat",0,"Blood Chestplate","armor/armor1.png",3,1250,ArmorType.chestplate);
Item.defineArmor(bllegg,"record_ward",0,"Blood leggings","armor/armor2.png",3,1000,ArmorType.leggings);
Item.defineArmor(blboots,"record_chirp",0,"Blood Boots","armor/armor1.png",2,1000,ArmorType.boots);

function attackHook(attacker, victim){
if(Player.getCarriedItem() == bloodexca){
use(14500,bloodexca);
dmg = 90;

if(Player.getCarriedItem() == blooddag){
use(8000,blooddag);
dmg = 35;

if(Player.getCarriedItem() == exca){
use(9000,exca);
dmg = 40;

Entity.setHealth(victim,Entity.getHealth(victim) - dmg);
}}

function use(maxDamage,id){
var pcid=Player.getCarriedItemData();
if(pcid!==maxDamage){
Entity.setCarriedItem(getPlayerEnt(),id,1,pcid+1);
}

else if(pcid==maxDamage){
Level.playSound(Player.getX(),Player.getY(),Player.getZ(),"random.break",2);
Entity.setCarriedItem(getPlayerEnt(),0,0,0);
}}

function modTick(){
if(Player.getCarriedItem()== 1001){
	if(Player.getCarriedItem()== 1007){
		if(Player.getCarriedItem()== 1008){
}}

function deathHook(murderer, victim){
Level.dropItem(Entity.getX(victim), Entity.getY(victim) + 1, Entity.getZ(victim), 1,1000,1,38);

-----
Help me please

**Comment by LawRence-G-38** [comment]
umm

**OLD CODE**
```javascript
function deathHook(murderer, victim){
Level.dropItem(Entity.getX(victim), Entity.getY(victim) + 1, Entity.getZ(victim), 1,1000,1,38);
```

**NEW CODE**
```javascript
function deathHook(murderer, victim){
Level.dropItem(Entity.getX(victim), Entity.getY(victim) + 1, Entity.getZ(victim), 1,1000,1,38);
}
```

**Comment by LawRence-G-38** [comment]
You just missed a character :)

**Comment by Aternix** [comment]
@DentedHarp90041

Thank you so much!
