### ISSUE TITLE
block luncher Pro and free will not open it crash's a sec into it then crashs

### ISSUE THREAD

**Issue by aXxG3TR3KTxX591** [zhuowei/MCPELauncher#1485]
running mcpe 1.9.0 latest block luncher trued beta and normal Fran Samsung galaxy Tab a 2016 android 8.1 and it crash's 2GB ram 8 core processor multi touch screen 16 by 8 screen 1920x1540 screen

**Comment by aXxG3TR3KTxX591** [comment]
a crash report a found not sure it's related
Time: 2018_05_16_09_45_16
Phone :SM-T350
Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.media.MediaPlayer.isPlaying()' on a null object reference
	at com.ijoysoft.videoplayer.activity.VideoPlayActivity.onClick(Unknown Source)
	at android.view.View.performClick(View.java:6308)
	at android.view.View$PerformClick.run(View.java:23969)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
