### ISSUE TITLE
Impossible to install a texture pack 

### ISSUE THREAD

**Issue by EvilLighty** [zhuowei/MCPELauncher#230]
Android version : 4.4.2
Blocklauncher version : 1.9.beta 4
Minecraft version : 0.11.0 beta 13

Everytime i tried to load a texture pack , i cet an error message : 
java.util.zip.ZipException: EOCD not found; not a Zip archive?
	at java.util.zip.ZipFile.readCentralDir(ZipFile.java:366)
	at java.util.zip.ZipFile.<init>(ZipFile.java:148)
	at java.util.zip.ZipFile.<init>(ZipFile.java:119)
	at net.zhuoweizhang.mcpelauncher.ZipTexturePack.<init>(ZipTexturePack.java:19)
	at net.zhuoweizhang.mcpelauncher.texture.TexturePackLoader.loadTexturePack(TexturePackLoader.java:79)
	at net.zhuoweizhang.mcpelauncher.texture.TexturePackLoader.loadTexturePacks(TexturePackLoader.java:34)
	at com.mojang.minecraftpe.MainActivity.loadTexturePack(MainActivity.java:1672)
	at com.mojang.minecraftpe.MainActivity.onCreate(MainActivity.java:306)
	at net.zhuoweizhang.mcpelauncher.LauncherAppActivity.onCreate(LauncherAppActivity.java:19)
	at android.app.Activity.performCreate(Activity.java:5122)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1150)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
	at android.app.ActivityThread.access$600(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5370)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by RandomAltThing** [comment]
This is probably caused by an **unknown texture pack format**. For example, one of the file names may be wrong or something.

**Comment by EvilLighty** [comment]
That strange because i tried with Dandelion pack , Redcraft , faithful , Smeeth4.5 , and Seus shaders . All of them are port to 0.11.0 and i have this error everytime .

**Comment by RandomAltThing** [comment]
Well the error is <code>not a Zip archive</code> so it must be something along the lines of wrong file format

**Comment by EvilLighty** [comment]
Huum well it's look like when my browser  download the zip file , he corrupted it .
I've fixed that by reinstall the browser
