### ISSUE TITLE
After update??? Need help with this error msg!

### ISSUE THREAD

**Issue by StolenSoul90** [zhuowei/MCPELauncher#450]
org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalArgumentException: The requested block texture daylight_detector_side:0 does not exist (a337ab1cbd0a78fcec12368d38643c21.js#300)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(a337ab1cbd0a78fcec12368d38643c21.js:300)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:253)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:179)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: The requested block texture daylight_detector_side:0 does not exist
	at net.zhuoweizhang.mcpelauncher.ScriptManager.verifyBlockTextures(ScriptManager.java:1271)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.access$1600(ScriptManager.java:53)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeBlockApi.defineBlock(ScriptManager.java:3202)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	... 11 more

Words of advice...not sure what this all means!

I'm using a Samsung Galaxy Tab 4 with the latest lollipop version. Also running Samsung Galaxy S5 with latest lollipop. Not sure if I'm getting this same error on the S5

**Comment by sliceofcode** [comment]
This is not an issue caused by BlockLauncher, so we cannot help you.
Please close this issue.

**Comment by Godsoft029** [comment]
Please deactivate all your mods and try again

**Comment by StolenSoul90** [comment]
No offense sliceofcode I never said it was a block launcher generated problem. I asked for some help on the message. @godsoft029 I did disable all of the mods I had and only enabled that 1 and still got the same message.

**Comment by Godsoft029** [comment]
Is it your own mod? If not, the mod is not compatible with this version of Blocklauncher. If it is your own mod, the texture "daylight_detector_side" is not aviable. Use another texture

**Comment by StolenSoul90** [comment]
Nope not one of mine...wish it was but I couldn't code to save my life lmao. Anyway thanks for the help godsoft029.

**Comment by zhuowei** [comment]
Also check if your texture pack is up to date: maybe the texture pack you're using doesn't have this texture (MCPE's built-in textures do have this texture)

**Comment by StolenSoul90** [comment]
Ya that particular mod is undergoing the process of being updated to 13.1
