### ISSUE TITLE
Mr.zhuowei why does this happen

### ISSUE THREAD

**Issue by 98brown** [zhuowei/MCPELauncher#830]
This cood keeps popping up even when there is no mod or other addons installed i reinstalled the game over and over can you please help 

Minecraft .0.14
Block luncher 1.12.0

java.lang.Exception: The addon "Too Many Items" (com.github.mcmrarm.tmi) is not compatible with Minecraft PE 0.14.0.
	at com.mojang.minecraftpe.MainActivity.loadNativeAddons(MainActivity.java:1700)
	at com.mojang.minecraftpe.MainActivity.onCreate(MainActivity.java:382)
	at net.zhuoweizhang.mcpelauncher.pro.LauncherProActivity.onCreate(LauncherProActivity.java:38)
	at android.app.Activity.performCreate(Activity.java:5411)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2259)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2384)
	at android.app.ActivityThread.access$800(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5252)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by DiegoGTRatty** [comment]
@98brown 
> java.lang.Exception: The addon "Too Many Items" (com.github.mcmrarm.tmi) is not compatible with Minecraft PE 0.14.0.

Try disabling Too Many Items. For what I know it was updated to 0.14.0, but it's separate from BlockLauncher now, which is a bit sad.

**Comment by officialmcpro32** [comment]
@DiegoGTRatty correction it has two versions 1 is in the playstore second is the separate all both are updated

**Comment by DiegoGTRatty** [comment]
Ohhh... My bad. XD
