### ISSUE TITLE
Block launcher won't let me use any mods!!!

### ISSUE THREAD

**Issue by anagirl1982** [zhuowei/MCPELauncher#876]
Here is a error code it has sent me 

org.mozilla.javascript.WrappedException: Wrapped net.zhuoweizhang.mcpelauncher.MissingTextureException: The item icon ruby:0 does not exist (Food Mod.js#6)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(Food Mod.js:6)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:266)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:191)
	at java.lang.Thread.run(Thread.java:841)
Caused by: net.zhuoweizhang.mcpelauncher.MissingTextureException: The item icon ruby:0 does not exist
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeModPEApi.setItem(ScriptManager.java:3289)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	... 11 more

**Comment by Black-DeathPE** [comment]
The mod you're using has a missing texture, so you need to activate a texture pack that is part of the mod or the mod is broken.

**Comment by zedman2000** [comment]
Please test this and close the issue if indeed you just needed a texture (which I agree seems to be the reason).

**Comment by Archie100** [comment]
I can use small mods like desmo guns but I get the same message as you ow nose every thing brokeorg.mozilla.javascript.WrappedException: Wrapped java.lang.RuntimeException: Invalid input in recipe: 33 is not a valid item. You must create the item before you can add it to a recipe. (Planes Mod.js#107)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(Planes Mod.js:107)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:254)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:180)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.RuntimeException: Invalid input in recipe: 33 is not a valid item. You must create the item before you can add it to a recipe.
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeItemApi.verifyAndAddShapedRecipe(ScriptManager.java:3200)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeItemApi.addShapedRecipe(ScriptManager.java:3186)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	... 11 more
org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalArgumentException: The item icon madera_hammer:0 does not exist
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(MoHammersByAxlTP.js)
	at script(MoHammersByAxlTP.js:30)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:261)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:187)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.IllegalArgumentException: The item icon madera_hammer:0 does not exist
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeModPEApi.setItem(ScriptManager.java:3035)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	... 11 more
Error occurred in script: ArmorMovementPEv2.0.js
org.mozilla.javascript.WrappedException: Wrapped java.lang.RuntimeException: Render type 1 does not exist (ArmorMovementPEv2.0.js#163)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script.featherFalling(ArmorMovementPEv2.0.js:163)
	at script.helihatFunction(ArmorMovementPEv2.0.js:551)
	at script.modTick(ArmorMovementPEv2.0.js:73)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.callScriptMethod(ScriptManager.java:278)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.tickCallback(ScriptManager.java:407)
	at dalvik.system.NativeStart.run(Native Method)
Caused by: java.lang.RuntimeException: Render type 1 does not exist
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeEntityApi.setRenderTypeImpl(ScriptManager.java:2759)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeEntityApi.setRenderType(ScriptManager.java:2743)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	... 11 more
java.lang.Exception: The addon "Toolbox for Minecraft: PE" (io.mrarm.mctoolbox) is not compatible with Minecraft PE 0.14.0.
	at com.mojang.minecraftpe.MainActivity.loadNativeAddons(MainActivity.java:1706)
	at com.mojang.minecraftpe.MainActivity.onCreate(MainActivity.java:388)
	at net.zhuoweizhang.mcpelauncher.pro.LauncherProActivity.onCreate(LauncherProActivity.java:38)
	at android.app.Activity.performCreate(Activity.java:5283)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
	at android.app.ActivityThread.access$700(ActivityThread.java:150)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:175)
	at android.app.ActivityThread.main(ActivityThread.java:5279)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
java.lang.Exception: The addon "Toolbox for Minecraft: PE" (io.mrarm.mctoolbox) is not compatible with Minecraft PE 0.14.0.
	at com.mojang.minecraftpe.MainActivity.loadNativeAddons(MainActivity.java:1706)
	at com.mojang.minecraftpe.MainActivity.onCreate(MainActivity.java:388)
	at net.zhuoweizhang.mcpelauncher.LauncherAppActivity.onCreate(LauncherAppActivity.java:24)
	at android.app.Activity.performCreate(Activity.java:5283)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
	at android.app.ActivityThread.access$700(ActivityThread.java:150)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:175)
	at android.app.ActivityThread.main(ActivityThread.java:5279)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalArgumentException: The item icon spawn:0 does not exist (SpaceCraftV2TP.js#11)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(SpaceCraftV2TP.js:11)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:261)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:187)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.IllegalArgumentException: The item icon spawn:0 does not exist
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeModPEApi.setItem(ScriptManager.java:3035)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	... 11 more
org.mozilla.javascript.WrappedException: Wrapped java.lang.RuntimeException: Invalid input in recipe: 33 is not a valid item. You must create the item before you can add it to a recipe. (Too_Much_TNT_PE_v_0.4.0.js#107)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(Too_Much_TNT_PE_v_0.4.0.js:107)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:254)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:180)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.RuntimeException: Invalid input in recipe: 33 is not a valid item. You must create the item before you can add it to a recipe.
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeItemApi.verifyAndAddShapedRecipe(ScriptManager.java:3200)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeItemApi.addShapedRecipe(ScriptManager.java:3186)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	... 11 more
org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalArgumentException: The item icon spawn:0 does not exist (SpaceCraftV2TP.js#11)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(SpaceCraftV2TP.js:11)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:253)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:179)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.IllegalArgumentException: The item icon spawn:0 does not exist
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeModPEApi.setItem(ScriptManager.java:2785)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	... 11 more
org.mozilla.javascript.WrappedException: Wrapped java.lang.RuntimeException: Invalid input in recipe: 33 is not a valid item. You must create the item before you can add it to a recipe. (Too_Much_TNT_PE_v_0.4.0.js#107)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(Too_Much_TNT_PE_v_0.4.0.js:107)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:254)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:180)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.RuntimeException: Invalid input in recipe: 33 is not a valid item. You must create the item before you can add it to a recipe.
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeItemApi.verifyAndAddShapedRecipe(ScriptManager.java:3200)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeItemApi.addShapedRecipe(ScriptManager.java:3186)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	... 11 more
org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalArgumentException: The item icon spawn:0 does not exist (SpaceCraftV2TP.js#11)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(SpaceCraftV2TP.js:11)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:261)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:187)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.IllegalArgumentException: The item icon spawn:0 does not exist
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeModPEApi.setItem(ScriptManager.java:3035)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	... 11 more
java.lang.Exception: The addon "Toolbox for Minecraft: PE" (io.mrarm.mctoolbox) is not compatible with Minecraft PE 0.14.0.
	at com.mojang.minecraftpe.MainActivity.loadNativeAddons(MainActivity.java:1706)
	at com.mojang.minecraftpe.MainActivity.onCreate(MainActivity.java:388)
	at net.zhuoweizhang.mcpelauncher.LauncherAppActivity.onCreate(LauncherAppActivity.java:24)
	at android.app.Activity.performCreate(Activity.java:5283)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
	at android.app.ActivityThread.access$700(ActivityThread.java:150)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:175)
	at android.app.ActivityThread.main(ActivityThread.java:5279)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
java.lang.Exception: The addon "Toolbox for Minecraft: PE" (io.mrarm.mctoolbox) is not compatible with Minecraft PE 0.14.0.
	at com.mojang.minecraftpe.MainActivity.loadNativeAddons(MainActivity.java:1706)
	at com.mojang.minecraftpe.MainActivity.onCreate(MainActivity.java:388)
	at net.zhuoweizhang.mcpelauncher.pro.LauncherProActivity.onCreate(LauncherProActivity.java:38)
	at android.app.Activity.performCreate(Activity.java:5283)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
	at android.app.ActivityThread.access$700(ActivityThread.java:150)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:175)
	at android.app.ActivityThread.main(ActivityThread.java:5279)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
Error occurred in script: ArmorMovementPEv2.0.js
org.mozilla.javascript.WrappedException: Wrapped java.lang.RuntimeException: Render type 1 does not exist (ArmorMovementPEv2.0.js#163)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script.featherFalling(ArmorMovementPEv2.0.js:163)
	at script.helihatFunction(ArmorMovementPEv2.0.js:551)
	at script.modTick(ArmorMovementPEv2.0.js:73)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.callScriptMethod(ScriptManager.java:278)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.tickCallback(ScriptManager.java:407)
	at dalvik.system.NativeStart.run(Native Method)
Caused by: java.lang.RuntimeException: Render type 1 does not exist
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeEntityApi.setRenderTypeImpl(ScriptManager.java:2759)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeEntityApi.setRenderType(ScriptManager.java:2743)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	... 11 more
org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalArgumentException: The item icon madera_hammer:0 does not exist
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(MoHammersByAxlTP.js)
	at script(MoHammersByAxlTP.js:30)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:261)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:187)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.IllegalArgumentException: The item icon madera_hammer:0 does not exist
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeModPEApi.setItem(ScriptManager.java:3035)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	... 11 more
org.mozilla.javascript.WrappedException: Wrapped java.lang.IllegalArgumentException: The item icon madera_hammer:0 does not exist
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(MoHammersByAxlTP.js)
	at script(MoHammersByAxlTP.js:30)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:261)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:187)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.IllegalArgumentException: The item icon madera_hammer:0 does not exist
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeModPEApi.setItem(ScriptManager.java:3035)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	... 11 more
org.mozilla.javascript.WrappedException: Wrapped java.lang.RuntimeException: Invalid input in recipe: 33 is not a valid item. You must create the item before you can add it to a recipe. (Planes Mod.js#107)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(Planes Mod.js:107)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:254)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:180)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.RuntimeException: Invalid input in recipe: 33 is not a valid item. You must create the item before you can add it to a recipe.
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeItemApi.verifyAndAddShapedRecipe(ScriptManager.java:3200)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeItemApi.addShapedRecipe(ScriptManager.java:3186)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	... 11 more

**Comment by Archie100** [comment]
Fix my moving problem and that 
thank you
