### ISSUE TITLE
Error with friend Mod

### ISSUE THREAD

**Issue by Lime2001** [zhuowei/MCPELauncher#911]
Error occurred in script: NpcModV2.js
org.mozilla.javascript.WrappedException: Wrapped java.lang.RuntimeException: setMaxHealth called on non-mob: entityType=0 (NpcModV2.js#89)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.FunctionObject.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script.useItem(NpcModV2.js:89)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.callScriptMethod(ScriptManager.java:283)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.useItemOnCallback(ScriptManager.java:295)
Caused by: java.lang.RuntimeException: setMaxHealth called on non-mob: entityType=0
	at net.zhuoweizhang.mcpelauncher.ScriptManager$NativeEntityApi.setMaxHealth(ScriptManager.java:2914)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	... 10 more

**Comment by Black-DeathPE** [comment]
Don't send Zhuowei these errors, send them to the mod makers.

**Comment by Lime2001** [comment]
Thank you.
