### ISSUE TITLE
It will not let me patch in the pixelmon mod for mcpe

### ISSUE THREAD

**Issue by pokepixelmon97** [zhuowei/MCPELauncher#997]
It will not let me patch in the pixel mon mod for mcpe i am useing a lG leon 

org.mozilla.javascript.WrappedException: Wrapped java.lang.RuntimeException: Font not found /sdcard/games/com.mojang/Pixelmon PE/minecraft.ttf (Pixelmon PE.js#32)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(Unknown Source)
	at org.mozilla.javascript.NativeJavaMethod.call(Unknown Source)
	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
	at script(Pixelmon PE.js:32)
	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:267)
	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:192)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: Font not found /sdcard/games/com.mojang/Pixelmon PE/minecraft.ttf
	at android.graphics.Typeface.createFromFile(Typeface.java:219)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	... 11 more

**Comment by DiegoGTRatty** [comment]
Apparently the mod is missing a font?

Try asking the mod creator for help first.
